import { CORE_DIRECT_PRO_CARDS } from "./core";
import { CAMPAIGN_TYPE_DIRECT_PRO_CARDS } from "./campaign-types";
import { CAMPAIGN_GROUP_SETTINGS_DIRECT_PRO_CARDS } from "./campaign-group-settings";
import { CAMPAIGN_HIERARCHY_LIFECYCLE_DIRECT_PRO_CARDS } from "./campaign-hierarchy";
import { INTERFACE_SURFACES_DIRECT_PRO_CARDS } from "./interface-surfaces";
import { AD_FORMATS_ELEMENTS_DIRECT_PRO_CARDS } from "./ad-formats-elements";
import { FORMATS_SHOWS_DIRECT_PRO_CARDS } from "./formats-shows";
import { TARGETING_SEMANTICS_DIRECT_PRO_CARDS } from "./targeting-semantics";
import { BILLING_AGENCY_LEGAL_ENTITIES_DIRECT_PRO_CARDS } from "./billing-agency-legal-entities";
import { STATISTICS_DIRECT_PRO_CARDS } from "./statistics";

export const DIRECT_PRO_KNOWLEDGE_CARDS = [
  ...CORE_DIRECT_PRO_CARDS,
  ...CAMPAIGN_TYPE_DIRECT_PRO_CARDS,
  ...CAMPAIGN_GROUP_SETTINGS_DIRECT_PRO_CARDS,
  ...CAMPAIGN_HIERARCHY_LIFECYCLE_DIRECT_PRO_CARDS,
  ...INTERFACE_SURFACES_DIRECT_PRO_CARDS,
  ...AD_FORMATS_ELEMENTS_DIRECT_PRO_CARDS,
  ...FORMATS_SHOWS_DIRECT_PRO_CARDS,
  ...TARGETING_SEMANTICS_DIRECT_PRO_CARDS,
  ...BILLING_AGENCY_LEGAL_ENTITIES_DIRECT_PRO_CARDS,
  ...STATISTICS_DIRECT_PRO_CARDS,
] as const;
